// 난청 치료 사례 데이터
export const hearingLossCases = [
  {
    id: "case_hearing_01",
    title: "60대 노인성 난청 개선 사례",
    description:
      "점진적으로 진행된 노인성 난청으로 일상 대화에 어려움을 겪으시던 60대 환자분이 3개월간의 한방치료로 청력이 개선되어 보청기 없이도 일상 대화가 가능해졌습니다.",
    date: "2024-01-10",
    categoryId: "cat_03",
    treatment_categories: { name: "난청" },
    order_num: 1,
    is_active: true,
  },
  {
    id: "case_hearing_02",
    title: "35세 돌발성 난청 치료",
    description:
      "갑자기 발생한 한쪽 귀의 청력 저하로 내원한 환자가 즉각적인 한방치료를 통해 2주 만에 청력이 80% 이상 회복되었습니다. 초기 집중 치료가 효과적이었던 사례입니다.",
    date: "2024-01-15",
    categoryId: "cat_03",
    treatment_categories: { name: "난청" },
    order_num: 2,
    is_active: true,
  },
  {
    id: "case_hearing_03",
    title: "45세 소음성 난청 개선",
    description: "공장 근무로 인한 만성 소음성 난청 환자가 6개월간의 한방치료를 통해 청력이 점진적으로 개선되었습니다. 이명 증상도 함께 호전되었습니다.",
    date: "2024-01-20",
    categoryId: "cat_03",
    treatment_categories: { name: "난청" },
    order_num: 3,
    is_active: true,
  },
  {
    id: "case_hearing_04",
    title: "28세 약물성 난청 치료",
    description: "항생제 부작용으로 인한 청력 저하를 겪은 젊은 환자가 한방치료를 통해 청력을 회복한 사례입니다. 3개월간의 치료로 정상 청력을 되찾았습니다.",
    date: "2024-01-25",
    categoryId: "cat_03",
    treatment_categories: { name: "난청" },
    order_num: 4,
    is_active: true,
  },
  {
    id: "case_hearing_05",
    title: "55세 편측성 난청 개선",
    description: "한쪽 귀의 청력만 저하된 환자가 4개월간의 한방치료로 양쪽 귀의 청력 차이가 크게 줄어들었습니다. 일상생활의 불편함이 현저히 감소했습니다.",
    date: "2024-02-01",
    categoryId: "cat_03",
    treatment_categories: { name: "난청" },
    order_num: 5,
    is_active: true,
  },
  {
    id: "case_hearing_06",
    title: "70대 양측성 난청 치료",
    description:
      "양쪽 귀 모두 심한 난청으로 보청기를 사용하던 어르신이 한방치료를 통해 보청기 의존도가 크게 줄어들었습니다. 가족들과의 대화가 훨씬 수월해졌습니다.",
    date: "2024-02-05",
    categoryId: "cat_03",
    treatment_categories: { name: "난청" },
    order_num: 6,
    is_active: true,
  },
  {
    id: "case_hearing_07",
    title: "42세 스트레스성 난청 개선",
    description:
      "심한 업무 스트레스로 인한 청력 저하와 이명을 겪던 직장인이 한약치료와 생활관리를 통해 증상이 개선되었습니다. 수면의 질도 함께 향상되었습니다.",
    date: "2024-02-10",
    categoryId: "cat_03",
    treatment_categories: { name: "난청" },
    order_num: 7,
    is_active: true,
  },
  {
    id: "case_hearing_08",
    title: "50대 만성 난청 치료",
    description:
      "20년 이상 지속된 만성 난청으로 고생하던 환자가 6개월간의 꾸준한 한방치료로 청력이 점진적으로 개선되었습니다. 특히 고음역대 청력이 향상되었습니다.",
    date: "2024-02-15",
    categoryId: "cat_03",
    treatment_categories: { name: "난청" },
    order_num: 8,
    is_active: true,
  },
  {
    id: "case_hearing_09",
    title: "65세 노인성 난청 개선",
    description: "노화로 인한 청력 저하로 TV 소리를 크게 틀어야 했던 환자가 한방치료를 통해 적정 볼륨으로도 시청이 가능해졌습니다. 가족 관계도 개선되었습니다.",
    date: "2024-02-20",
    categoryId: "cat_03",
    treatment_categories: { name: "난청" },
    order_num: 9,
    is_active: true,
  },
  {
    id: "case_hearing_10",
    title: "38세 급성 난청 치료",
    description: "갑작스러운 청력 상실로 응급실을 다녀온 후 내원한 환자가 한방치료를 통해 3주 만에 정상 청력을 회복했습니다. 어지럼증도 함께 개선되었습니다.",
    date: "2024-02-25",
    categoryId: "cat_03",
    treatment_categories: { name: "난청" },
    order_num: 10,
    is_active: true,
  },
];
