// 기타 이비인후과 질환 치료 사례 데이터
export const otherCases = [
  {
    id: "case_others_01",
    title: "45세 후각 장애 치료",
    description: "코로나19 감염 후 6개월간 지속된 후각 장애가 한방치료를 통해 점진적으로 개선되어 일상적인 냄새를 맡을 수 있게 되었습니다.",
    date: "2024-01-10",
    categoryId: "cat_08",
    treatment_categories: { name: "기타 이비인후과 질환" },
    order_num: 1,
    is_active: true,
  },
  {
    id: "case_others_02",
    title: "55세 인후두 역류질환 개선",
    description: "만성적인 인후두 역류로 인한 목 불편감과 기침이 한방치료를 통해 호전되었습니다. 식습관 개선도 함께 이루어졌습니다.",
    date: "2024-01-15",
    categoryId: "cat_08",
    treatment_categories: { name: "기타 이비인후과 질환" },
    order_num: 2,
    is_active: true,
  },
  {
    id: "case_others_03",
    title: "38세 성대 결절 치료",
    description: "과도한 음성 사용으로 인한 성대 결절이 한방치료와 음성 관리를 통해 개선되었습니다. 목소리 질도 함께 향상되었습니다.",
    date: "2024-01-20",
    categoryId: "cat_08",
    treatment_categories: { name: "기타 이비인후과 질환" },
    order_num: 3,
    is_active: true,
  },
  {
    id: "case_others_04",
    title: "28세 구강 건조증 개선",
    description: "스트레스로 인한 만성 구강 건조증이 한약 치료를 통해 호전되었습니다. 수면의 질도 함께 개선되었습니다.",
    date: "2024-01-25",
    categoryId: "cat_08",
    treatment_categories: { name: "기타 이비인후과 질환" },
    order_num: 4,
    is_active: true,
  },
  {
    id: "case_others_05",
    title: "62세 연하 장애 치료",
    description: "뇌졸중 후유증으로 인한 연하 장애가 한방치료를 통해 개선되어 식사가 수월해졌습니다. 영양 상태도 호전되었습니다.",
    date: "2024-02-01",
    categoryId: "cat_08",
    treatment_categories: { name: "기타 이비인후과 질환" },
    order_num: 5,
    is_active: true,
  },
  {
    id: "case_others_06",
    title: "35세 구취 증상 개선",
    description: "만성적인 구취로 대인관계에 어려움을 겪던 환자가 한방치료를 통해 증상이 개선되었습니다. 자신감도 회복되었습니다.",
    date: "2024-02-05",
    categoryId: "cat_08",
    treatment_categories: { name: "기타 이비인후과 질환" },
    order_num: 6,
    is_active: true,
  },
  {
    id: "case_others_07",
    title: "48세 후비루 증후군 치료",
    description: "지속적인 후비루로 불편함을 겪던 환자가 한방치료를 통해 증상이 감소하고 목 불편감도 개선되었습니다.",
    date: "2024-02-10",
    categoryId: "cat_08",
    treatment_categories: { name: "기타 이비인후과 질환" },
    order_num: 7,
    is_active: true,
  },
  {
    id: "case_others_08",
    title: "52세 성대 마비 개선",
    description: "갑상선 수술 후 발생한 성대 마비가 한방치료를 통해 점진적으로 호전되어 음성이 개선되었습니다.",
    date: "2024-02-15",
    categoryId: "cat_08",
    treatment_categories: { name: "기타 이비인후과 질환" },
    order_num: 8,
    is_active: true,
  },
  {
    id: "case_others_09",
    title: "33세 구강 점막 질환 치료",
    description: "재발성 아프타성 구내염으로 고생하던 환자가 한방치료를 통해 재발이 감소하고 통증도 줄었습니다.",
    date: "2024-02-20",
    categoryId: "cat_08",
    treatment_categories: { name: "기타 이비인후과 질환" },
    order_num: 9,
    is_active: true,
  },
  {
    id: "case_others_10",
    title: "58세 미각 장애 개선",
    description: "약물 부작용으로 인한 미각 장애가 한방치료를 통해 점진적으로 개선되어 정상적인 맛을 느낄 수 있게 되었습니다.",
    date: "2024-02-25",
    categoryId: "cat_08",
    treatment_categories: { name: "기타 이비인후과 질환" },
    order_num: 10,
    is_active: true,
  },
];
