// 중이염 치료 사례 데이터
export const otitisMediaCases = [
  {
    id: "case_otitis_01",
    title: "5세 아동 만성 중이염 치료 사례",
    description:
      "잦은 중이염으로 수술을 고민하던 5세 아동이 한약 치료를 통해 면역력이 증진되어 중이염 재발이 크게 감소했습니다. 6개월간의 치료로 항생제 없이도 건강한 상태를 유지하고 있습니다.",
    date: "2024-01-10",
    categoryId: "cat_04",
    treatment_categories: { name: "중이염" },
    order_num: 1,
    is_active: true,
  },
  {
    id: "case_otitis_02",
    title: "3세 영유아 급성 중이염 치료",
    description:
      "고열과 함께 시작된 급성 중이염으로 고생하던 3세 아이가 한방치료를 통해 빠른 회복을 보였습니다. 면역력 강화로 재발 방지에도 효과를 보았습니다.",
    date: "2024-01-15",
    categoryId: "cat_04",
    treatment_categories: { name: "중이염" },
    order_num: 2,
    is_active: true,
  },
  {
    id: "case_otitis_03",
    title: "7세 삼출성 중이염 개선",
    description: "3개월 이상 지속된 삼출성 중이염으로 청력 저하를 겪던 7세 아동이 한방치료를 통해 삼출액이 감소하고 청력이 회복되었습니다.",
    date: "2024-01-20",
    categoryId: "cat_04",
    treatment_categories: { name: "중이염" },
    order_num: 3,
    is_active: true,
  },
  {
    id: "case_otitis_04",
    title: "4세 반복성 중이염 치료",
    description: "감기만 걸리면 중이염이 재발하던 4세 아이가 한약 치료로 면역력이 증진되어 감기와 중이염 모두 잘 걸리지 않게 되었습니다.",
    date: "2024-01-25",
    categoryId: "cat_04",
    treatment_categories: { name: "중이염" },
    order_num: 4,
    is_active: true,
  },
  {
    id: "case_otitis_05",
    title: "8세 만성 중이염 개선",
    description: "2년 넘게 만성 중이염으로 고생하던 8세 아동이 4개월간의 한방치료로 증상이 크게 호전되었습니다. 이관 기능도 함께 개선되었습니다.",
    date: "2024-02-01",
    categoryId: "cat_04",
    treatment_categories: { name: "중이염" },
    order_num: 5,
    is_active: true,
  },
  {
    id: "case_otitis_06",
    title: "6세 항생제 내성 중이염 치료",
    description: "항생제 치료에 반응하지 않던 중이염 환아가 한방치료를 통해 증상이 개선되었습니다. 면역력 강화로 재발도 크게 감소했습니다.",
    date: "2024-02-05",
    categoryId: "cat_04",
    treatment_categories: { name: "중이염" },
    order_num: 6,
    is_active: true,
  },
  {
    id: "case_otitis_07",
    title: "2세 영아 중이염 치료",
    description: "잦은 중이염으로 밤잠을 설치던 2세 아기가 한약 치료를 통해 증상이 호전되었습니다. 보채는 횟수가 크게 줄고 수면의 질도 개선되었습니다.",
    date: "2024-02-10",
    categoryId: "cat_04",
    treatment_categories: { name: "중이염" },
    order_num: 7,
    is_active: true,
  },
  {
    id: "case_otitis_08",
    title: "9세 알레르기성 중이염 개선",
    description: "알레르기 비염과 함께 중이염이 자주 발생하던 9세 아동이 한방치료로 두 증상 모두 개선되었습니다. 집중력도 함께 향상되었습니다.",
    date: "2024-02-15",
    categoryId: "cat_04",
    treatment_categories: { name: "중이염" },
    order_num: 8,
    is_active: true,
  },
  {
    id: "case_otitis_09",
    title: "1세 영아 급성 중이염 치료",
    description: "첫 중이염으로 고열과 통증을 겪던 1세 아기가 한방치료를 통해 빠르게 회복되었습니다. 보호자가 안심하고 치료받을 수 있었습니다.",
    date: "2024-02-20",
    categoryId: "cat_04",
    treatment_categories: { name: "중이염" },
    order_num: 9,
    is_active: true,
  },
  {
    id: "case_otitis_10",
    title: "10세 수영 후 중이염 치료",
    description: "수영 후 발생한 외이도염과 중이염으로 내원한 10세 아동이 한방치료를 통해 2주 만에 완전히 회복되었습니다. 예방 교육도 함께 진행했습니다.",
    date: "2024-02-25",
    categoryId: "cat_04",
    treatment_categories: { name: "중이염" },
    order_num: 10,
    is_active: true,
  },
];
