// 비염 치료 사례 데이터
export const rhinitisCases = [
  {
    id: "case_rhinitis_01",
    title: "15세 청소년 알레르기 비염 치료",
    description:
      "심한 알레르기 비염으로 학교생활에 어려움을 겪던 중학생이 체질 개선을 위한 한약 치료로 증상이 크게 호전되었습니다. 특히 봄철 꽃가루 알레르기 반응이 현저히 감소했습니다.",
    date: "2024-01-10",
    categoryId: "cat_05",
    treatment_categories: { name: "비염" },
    order_num: 1,
    is_active: true,
  },
  {
    id: "case_rhinitis_02",
    title: "8세 소아 만성 비염 개선",
    description: "잦은 콧물과 코막힘으로 수면 장애를 겪던 8세 아동이 한방치료를 통해 증상이 개선되었습니다. 집중력이 향상되어 학습 능력도 좋아졌습니다.",
    date: "2024-01-15",
    categoryId: "cat_05",
    treatment_categories: { name: "비염" },
    order_num: 2,
    is_active: true,
  },
  {
    id: "case_rhinitis_03",
    title: "35세 직장인 비염 치료",
    description: "에어컨 바람으로 악화되는 비염 증상으로 업무에 지장을 겪던 직장인이 한약 치료로 증상이 호전되어 쾌적한 근무가 가능해졌습니다.",
    date: "2024-01-20",
    categoryId: "cat_05",
    treatment_categories: { name: "비염" },
    order_num: 3,
    is_active: true,
  },
  {
    id: "case_rhinitis_04",
    title: "25세 꽃가루 알레르기 개선",
    description: "봄철만 되면 심해지는 알레르기 비염으로 고생하던 대학생이 한방치료를 통해 꽃가루 알레르기 반응이 크게 감소했습니다.",
    date: "2024-01-25",
    categoryId: "cat_05",
    treatment_categories: { name: "비염" },
    order_num: 4,
    is_active: true,
  },
  {
    id: "case_rhinitis_05",
    title: "45세 만성 비염 치료",
    description: "10년 이상 비염 약을 복용해온 환자가 한방치료를 통해 약물 의존도가 크게 줄었습니다. 비강 점막 기능도 함께 개선되었습니다.",
    date: "2024-02-01",
    categoryId: "cat_05",
    treatment_categories: { name: "비염" },
    order_num: 5,
    is_active: true,
  },
  {
    id: "case_rhinitis_06",
    title: "12세 학생 비염 개선",
    description: "잦은 재채기와 콧물로 수업 집중에 어려움을 겪던 초등학생이 한약 치료로 증상이 호전되어 학교생활이 훨씬 편안해졌습니다.",
    date: "2024-02-05",
    categoryId: "cat_05",
    treatment_categories: { name: "비염" },
    order_num: 6,
    is_active: true,
  },
  {
    id: "case_rhinitis_07",
    title: "28세 운동선수 비염 치료",
    description: "실외 운동 시 심해지는 비염으로 운동 수행에 어려움을 겪던 선수가 한방치료를 통해 증상이 개선되어 정상적인 훈련이 가능해졌습니다.",
    date: "2024-02-10",
    categoryId: "cat_05",
    treatment_categories: { name: "비염" },
    order_num: 7,
    is_active: true,
  },
  {
    id: "case_rhinitis_08",
    title: "50대 혈관운동성 비염 개선",
    description: "온도 변화에 민감하게 반응하는 비염으로 고생하던 50대 환자가 한약 치료로 증상이 안정되어 일상생활이 훨씬 편해졌습니다.",
    date: "2024-02-15",
    categoryId: "cat_05",
    treatment_categories: { name: "비염" },
    order_num: 8,
    is_active: true,
  },
  {
    id: "case_rhinitis_09",
    title: "6세 소아 비염 치료",
    description: "잦은 감기와 비염으로 어린이집 생활에 어려움을 겪던 아이가 한방치료로 면역력이 증진되어 건강하게 지내게 되었습니다.",
    date: "2024-02-20",
    categoryId: "cat_05",
    treatment_categories: { name: "비염" },
    order_num: 9,
    is_active: true,
  },
  {
    id: "case_rhinitis_10",
    title: "32세 임산부 비염 개선",
    description: "임신 중 악화된 비염으로 고생하던 임산부가 안전한 한방치료를 통해 증상이 개선되어 편안한 임신 생활이 가능해졌습니다.",
    date: "2024-02-25",
    categoryId: "cat_05",
    treatment_categories: { name: "비염" },
    order_num: 10,
    is_active: true,
  },
];
