// 축농증 치료 사례 데이터
export const sinusitisCases = [
  {
    id: "case_sinusitis_01",
    title: "35세 만성 축농증 치료",
    description: "5년 이상 지속된 만성 축농증으로 고생하던 환자가 3개월간의 한방치료를 통해 비강 내 염증이 감소하고 두통 증상도 크게 개선되었습니다.",
    date: "2024-01-10",
    categoryId: "cat_06",
    treatment_categories: { name: "축농증" },
    order_num: 1,
    is_active: true,
  },
  {
    id: "case_sinusitis_02",
    title: "28세 급성 축농증 개선",
    description: "심한 감기 후 발생한 급성 축농증으로 내원한 환자가 한약 치료와 침 치료를 병행하여 2주 만에 증상이 호전되었습니다.",
    date: "2024-01-15",
    categoryId: "cat_06",
    treatment_categories: { name: "축농증" },
    order_num: 2,
    is_active: true,
  },
  {
    id: "case_sinusitis_03",
    title: "45세 알레르기성 축농증 치료",
    description: "알레르기 비염과 함께 악화된 축농증으로 고생하던 환자가 한방치료를 통해 알레르기 반응이 감소하고 부비동 염증도 개선되었습니다.",
    date: "2024-01-20",
    categoryId: "cat_06",
    treatment_categories: { name: "축농증" },
    order_num: 3,
    is_active: true,
  },
  {
    id: "case_sinusitis_04",
    title: "52세 재발성 축농증 개선",
    description: "수술 후에도 재발을 반복하던 축농증 환자가 6개월간의 한방치료로 재발 없이 건강한 상태를 유지하고 있습니다.",
    date: "2024-01-25",
    categoryId: "cat_06",
    treatment_categories: { name: "축농증" },
    order_num: 4,
    is_active: true,
  },
  {
    id: "case_sinusitis_05",
    title: "40세 직장인 축농증 치료",
    description: "과로와 스트레스로 악화된 축농증 환자가 한약 치료와 생활 관리를 통해 증상이 개선되고 면역력도 향상되었습니다.",
    date: "2024-02-01",
    categoryId: "cat_06",
    treatment_categories: { name: "축농증" },
    order_num: 5,
    is_active: true,
  },
  {
    id: "case_sinusitis_06",
    title: "33세 치과 치료 후 축농증 개선",
    description: "치과 치료 후 발생한 상악동염으로 고생하던 환자가 한방치료를 통해 염증이 감소하고 통증도 크게 완화되었습니다.",
    date: "2024-02-05",
    categoryId: "cat_06",
    treatment_categories: { name: "축농증" },
    order_num: 6,
    is_active: true,
  },
  {
    id: "case_sinusitis_07",
    title: "48세 비중격 만곡증 동반 축농증 치료",
    description: "비중격 만곡증으로 인해 악화된 축농증 환자가 한방치료를 통해 비강 기능이 개선되고 축농증 증상도 호전되었습니다.",
    date: "2024-02-10",
    categoryId: "cat_06",
    treatment_categories: { name: "축농증" },
    order_num: 7,
    is_active: true,
  },
  {
    id: "case_sinusitis_08",
    title: "25세 수영 후 발생한 축농증 개선",
    description: "수영장에서 물이 들어가 발생한 급성 축농증 환자가 한방치료로 빠른 회복을 보였습니다. 예방 교육도 함께 진행했습니다.",
    date: "2024-02-15",
    categoryId: "cat_06",
    treatment_categories: { name: "축농증" },
    order_num: 8,
    is_active: true,
  },
  {
    id: "case_sinusitis_09",
    title: "38세 항생제 내성 축농증 치료",
    description: "장기간의 항생제 사용으로 내성이 생긴 축농증 환자가 한방치료를 통해 자연스러운 치유가 이루어졌습니다.",
    date: "2024-02-20",
    categoryId: "cat_06",
    treatment_categories: { name: "축농증" },
    order_num: 9,
    is_active: true,
  },
  {
    id: "case_sinusitis_10",
    title: "42세 계절성 축농증 개선",
    description: "환절기만 되면 악화되던 축농증 환자가 한방치료를 통해 면역력이 증진되어 계절 변화에도 잘 견디게 되었습니다.",
    date: "2024-02-25",
    categoryId: "cat_06",
    treatment_categories: { name: "축농증" },
    order_num: 10,
    is_active: true,
  },
];
