// 편도염 치료 사례 데이터
export const tonsillitisCases = [
  {
    id: "case_tonsillitis_01",
    title: "25세 만성 편도염 치료",
    description: "잦은 편도염으로 수술을 권유받았던 환자가 3개월간의 한방치료를 통해 재발이 크게 감소하고 면역력이 향상되었습니다.",
    date: "2024-01-10",
    categoryId: "cat_07",
    treatment_categories: { name: "편도염" },
    order_num: 1,
    is_active: true,
  },
  {
    id: "case_tonsillitis_02",
    title: "8세 소아 급성 편도염 개선",
    description: "고열을 동반한 급성 편도염으로 내원한 어린이가 한약 치료를 통해 빠른 회복을 보였습니다. 면역력 강화로 재발도 예방했습니다.",
    date: "2024-01-15",
    categoryId: "cat_07",
    treatment_categories: { name: "편도염" },
    order_num: 2,
    is_active: true,
  },
  {
    id: "case_tonsillitis_03",
    title: "32세 재발성 편도염 치료",
    description: "매년 3-4회 이상 재발하던 편도염이 한방치료를 통해 발병 빈도가 크게 줄었습니다. 항생제 사용도 현저히 감소했습니다.",
    date: "2024-01-20",
    categoryId: "cat_07",
    treatment_categories: { name: "편도염" },
    order_num: 3,
    is_active: true,
  },
  {
    id: "case_tonsillitis_04",
    title: "15세 청소년 편도염 개선",
    description: "학업 스트레스로 자주 재발하던 편도염이 한약 치료와 생활 관리를 통해 호전되었습니다. 피로 회복도 함께 이루어졌습니다.",
    date: "2024-01-25",
    categoryId: "cat_07",
    treatment_categories: { name: "편도염" },
    order_num: 4,
    is_active: true,
  },
  {
    id: "case_tonsillitis_05",
    title: "42세 만성 편도비대 치료",
    description: "만성적인 편도 비대로 코골이와 수면 무호흡이 있던 환자가 한방치료를 통해 편도 크기가 감소하고 수면의 질이 개선되었습니다.",
    date: "2024-02-01",
    categoryId: "cat_07",
    treatment_categories: { name: "편도염" },
    order_num: 5,
    is_active: true,
  },
  {
    id: "case_tonsillitis_06",
    title: "5세 아동 편도염 치료",
    description: "잦은 편도염으로 어린이집 생활이 힘들었던 아이가 한방치료를 통해 증상이 개선되고 면역력이 강화되었습니다.",
    date: "2024-02-05",
    categoryId: "cat_07",
    treatment_categories: { name: "편도염" },
    order_num: 6,
    is_active: true,
  },
  {
    id: "case_tonsillitis_07",
    title: "28세 항생제 내성 편도염 개선",
    description: "항생제 치료에 반응하지 않던 만성 편도염이 한방치료를 통해 자연스러운 치유가 이루어졌습니다. 체질 개선도 함께 진행되었습니다.",
    date: "2024-02-10",
    categoryId: "cat_07",
    treatment_categories: { name: "편도염" },
    order_num: 7,
    is_active: true,
  },
  {
    id: "case_tonsillitis_08",
    title: "35세 직장인 편도염 치료",
    description: "과로와 음주로 악화된 편도염이 한약 치료와 생활 습관 개선을 통해 호전되었습니다. 전반적인 컨디션도 좋아졌습니다.",
    date: "2024-02-15",
    categoryId: "cat_07",
    treatment_categories: { name: "편도염" },
    order_num: 8,
    is_active: true,
  },
  {
    id: "case_tonsillitis_09",
    title: "12세 학생 편도염 개선",
    description: "감기만 걸리면 심해지던 편도염이 한방치료를 통해 호전되었습니다. 면역력 강화로 감기 감염도 줄었습니다.",
    date: "2024-02-20",
    categoryId: "cat_07",
    treatment_categories: { name: "편도염" },
    order_num: 9,
    is_active: true,
  },
  {
    id: "case_tonsillitis_10",
    title: "45세 만성 편도염 치료",
    description: "15년 이상 지속된 만성 편도염이 6개월간의 한방치료를 통해 크게 호전되었습니다. 목 통증과 피로감도 함께 개선되었습니다.",
    date: "2024-02-25",
    categoryId: "cat_07",
    treatment_categories: { name: "편도염" },
    order_num: 10,
    is_active: true,
  },
];
